// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package repositories

import (
	"github.com/jake-hansen/agora/config"
	"github.com/jake-hansen/agora/database"
)

// Injectors from wire.go:

func BuildUserRepository() *UserRepository {
	viper := config.ProvideViper()
	db := database.ProvideDB(viper)
	userRepository := ProvideUserRepository(db)
	return userRepository
}
