// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package jwtservice

import (
	"github.com/jake-hansen/agora/config"
)

// Injectors from injector.go:

func Build() (*JWTServiceImpl, error) {
	viper := config.Provide()
	jwtserviceConfig, err := Cfg(viper)
	if err != nil {
		return nil, err
	}
	jwtServiceImpl := Provide(jwtserviceConfig)
	return jwtServiceImpl, nil
}

func BuildTest(cfg Config) (*JWTServiceImpl, error) {
	jwtserviceConfig, err := CfgTest(cfg)
	if err != nil {
		return nil, err
	}
	jwtServiceImpl := Provide(jwtserviceConfig)
	return jwtServiceImpl, nil
}
