// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package meetingplatformservice

import (
	"github.com/jake-hansen/agora/domain"
)

// Injectors from injector.go:

func BuildTest(repo domain.MeetingPlatformRepository, configuredPlatforms []*domain.MeetingPlatform) *MeetingPlatformService {
	meetingPlatformService := Provide(repo, configuredPlatforms)
	return meetingPlatformService
}
