dist: focal

os: linux

language: go

services:
  - docker

go:
  - "1.15"

before_script:
  - docker --version
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

script:
  - make unit-test

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region $AWS_ECR_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
  - LAST_COMMIT_SHA=$(git rev-parse --short HEAD)
  - make build-image
  - docker tag agora:latest $AWS_ECR_URL/agora:latest
  - docker tag agora:latest $AWS_ECR_URL/agora:$LAST_COMMIT_SHA
  - docker push $AWS_ECR_URL/agora:$LAST_COMMIT_SHA
  - docker push $AWS_ECR_URL/agora:latest