// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package log

import (
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Build(v *viper.Viper) (*Log, func(), error) {
	config := Cfg(v)
	log, cleanup, err := Provide(config)
	if err != nil {
		return nil, nil, err
	}
	return log, func() {
		cleanup()
	}, nil
}
