// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package log

import (
	"github.com/jake-hansen/agora/config"
)

// Injectors from injector.go:

func Build() (*Log, func(), error) {
	viper := config.Provide()
	zapConfig := Cfg(viper)
	log, cleanup, err := Provide(zapConfig)
	if err != nil {
		return nil, nil, err
	}
	return log, func() {
		cleanup()
	}, nil
}
