// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package meetingproviderrepomock

// Injectors from injector.go:

func Build() *MeetingProviderRepository {
	meetingProviderRepository := Provide()
	return meetingProviderRepository
}
