// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package userrepomock

// Injectors from injector.go:

func Build() *UserRepository {
	userRepository := Provide()
	return userRepository
}
