// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package authmiddleware

import (
	"github.com/jake-hansen/agora/domain"
	"net/http"
)

// Injectors from injector.go:

func BuildTest(authService domain.AuthService, parseToken func(r *http.Request) (*domain.Token, error)) *AuthMiddleware {
	authMiddleware := Provide(authService, parseToken)
	return authMiddleware
}
