// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/jake-hansen/agora/config"
	"github.com/jake-hansen/agora/database"
	"github.com/jake-hansen/agora/database/repositories/userrepo"
	"github.com/jake-hansen/agora/services/jwtservice"
	"github.com/jake-hansen/agora/services/simpleauthservice"
	"github.com/jake-hansen/agora/services/userservice"
)

// Injectors from wire.go:

func BuildSimpleAuthService() (*simpleauthservice.SimpleAuthService, error) {
	viper := config.ProvideViper()
	jwtConfig, err := jwtservice.ProvideJWTConfig(viper)
	if err != nil {
		return nil, err
	}
	jwtService := jwtservice.ProvideJWTService(jwtConfig)
	db := database.ProvideDB(viper)
	userRepository := userrepo.ProvideUserRepository(db)
	userService := userservice.ProvideUserService(userRepository)
	simpleAuthService := simpleauthservice.ProvideSimpleAuthService(jwtService, userService)
	return simpleAuthService, nil
}
