// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/jake-hansen/agora/config"
	"github.com/jake-hansen/agora/database"
	"github.com/jake-hansen/agora/database/repositories"
)

// Injectors from wire.go:

func BuildSimpleAuthService() (*SimpleAuthService, error) {
	viper := config.ProvideViper()
	jwtConfig, err := ProvideJWTConfig(viper)
	if err != nil {
		return nil, err
	}
	jwtService := ProvideJWTService(jwtConfig)
	db := database.ProvideDB(viper)
	userRepository := repositories.ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	simpleAuthService := ProvideSimpleAuthService(jwtService, userService)
	return simpleAuthService, nil
}
