// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"github.com/jake-hansen/agora/api/handlers"
	"github.com/jake-hansen/agora/api/handlers/authhandler"
	"github.com/jake-hansen/agora/api/handlers/userhandler"
	"github.com/jake-hansen/agora/api/middleware"
	"github.com/jake-hansen/agora/config"
	"github.com/jake-hansen/agora/database"
	"github.com/jake-hansen/agora/database/repositories/userrepo"
	"github.com/jake-hansen/agora/router"
	handlers2 "github.com/jake-hansen/agora/router/handlers"
	"github.com/jake-hansen/agora/services/jwtservice"
	"github.com/jake-hansen/agora/services/simpleauthservice"
	"github.com/jake-hansen/agora/services/userservice"
)

// Injectors from injector.go:

func Build() (*Server, func(), error) {
	viper := config.Provide()
	serverConfig, err := Cfg(viper)
	if err != nil {
		return nil, nil, err
	}
	v := middleware.ProvideAllProductionMiddleware()
	jwtserviceConfig, err := jwtservice.Cfg(viper)
	if err != nil {
		return nil, nil, err
	}
	jwtServiceImpl := jwtservice.Provide(jwtserviceConfig)
	databaseConfig, err := database.Cfg(viper)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := database.ProvideGORM(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	manager, err := database.Provide(databaseConfig, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := userrepo.Provide(manager)
	userService := userservice.Provide(userRepository)
	simpleAuthService := simpleauthservice.Provide(jwtServiceImpl, userService)
	authHandler := authhandler.Provide(simpleAuthService)
	userHandler := userhandler.Provide(userService)
	v2 := handlers.ProvideAllProductionHandlers(authHandler, userHandler)
	handlerManager := handlers2.ProvideHandlerManager(v2)
	routerConfig, err := router.Cfg(viper, v, handlerManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	routerRouter := router.Provide(routerConfig)
	server := Provide(serverConfig, routerRouter)
	return server, func() {
		cleanup()
	}, nil
}
