version: "3.9"
services:
  db:
    image: mysql:latest
    networks:
      new:
        aliases:
          - database
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agora
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  migrate:
    image: agora-migrate:latest
    networks:
      - new
    build: ./migrations
    links:
      - db
    depends_on: 
      db:
        condition: service_healthy
    environment: 
      - DATABASE_TYPE=mysql
      - USER=root
      - PASSWORD=password
      - PROTOCOL=tcp
      - HOST=database
      - PORT=3306
networks:
  new:
  