// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package database

import (
	"github.com/jake-hansen/agora/config"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildDB() *gorm.DB {
	viper := config.ProvideViper()
	db := ProvideDB(viper)
	return db
}
