// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package database

import (
	"github.com/jake-hansen/agora/log"
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Build(v *viper.Viper, log2 *log.Log) (*Manager, func(), error) {
	config, err := Cfg(v, log2)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideGORM(config)
	if err != nil {
		return nil, nil, err
	}
	manager, err := Provide(config, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return manager, func() {
		cleanup()
	}, nil
}

func BuildTest(cfg Config) (*MockManager, func(), error) {
	config, err := CfgTest(cfg)
	if err != nil {
		return nil, nil, err
	}
	mockManager, cleanup, err := ProvideMock(config)
	if err != nil {
		return nil, nil, err
	}
	return mockManager, func() {
		cleanup()
	}, nil
}
