// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package meetingproviderservice

import (
	"github.com/jake-hansen/agora/domain"
)

// Injectors from injector.go:

func BuildTest(repo domain.MeetingProviderRepository) *MeetingProviderService {
	meetingProviderService := Provide(repo)
	return meetingProviderService
}
