// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package jwtservicemock

// Injectors from injector.go:

func Build() *Service {
	service := Provide()
	return service
}
