server:
  # Address the API should listen on. This should be in the format of
  # {ADDRESS}:{PORT}. If the address is omitted, the API will listen
  # on all addresses.
  address:
api:
  endpoints:
    # This value will be prepended on all endpoints. For example, if
    # The API normally registers an endpoint /v1/example, and the root
    # value is set to 'myroot', then the new registed endpoint will be
    # /myroot/v1/example.
    root:
  cors:
    # This sets how long the results fo a preflight request can be cached.
    # Values should be in human readable format. For example '30m', '1h',
    # or '1d', meaning 30 minutes, 1 hour, and 1 day, respectively.
    maxage:
    origins:
      # List of allowed origins.
      allowed:
# This is the environment the application should run in. This controls
# various things but mainly logging levels. Valid values for this property
# are 'dev' or 'prod'.
environment:
jwtservice:
  # This is the duration of the JWT token that is issued when using the 
  # built in authentication service. Values should be in human readable
  # format. For example '30m', '1h', or '1d', meaning 30 minutes, 1 hour,
  # and 1 day, respectively.
  duration: 
  # Issuer value to be set within signed JWTs.
  issuer:
  # Key to use to sign JWTs.
  signingkey:
database:
  # Type of database that will be used. Valid values are 'mysql'.
  type: 
  # Username to use to connect to the database.
  username: 
  # Password to use to connect to the database.
  password: 
  # Protocol to use to connect to the database. Should normally be 'TCP'
  # unless another protocol is needed for a specific purpose.
  protocol: 
  # Hostname of the server the database is running on.
  host: 
  # Port to use to connect to the database.
  port:
  # Name of the database or schema to use.
  name:
# Configuration details for meeting platforms.
platforms:
  zoom:
    oauth:
      url:
        # URL that users should be redirected to after authenticating with
        # the authorization server.
        redirect: 
        # URL that users should be directed to in order to authenticate with
        # the authorizaton server.
        auth: 
        # URL to exhchange an authorization code for access and refresh tokens.
        token: 
      client:
        # ID of this client on the authorization server.
        id: 
        # Secret of this client on the authorization server.
        secret: 
        # List of scopes to be requested during authorization.
        scopes:
  