// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package config

import (
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Build() *viper.Viper {
	viperViper := Provide()
	return viperViper
}
