// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package config

import (
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func BuildConfig() *viper.Viper {
	viperViper := ProvideViper()
	return viperViper
}
