// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package jwt

import (
	"github.com/jake-hansen/agora/config"
)

// Injectors from injector.go:

func Build() (*Service, error) {
	viper := config.ProvideViper()
	jwtConfig, err := Cfg(viper)
	if err != nil {
		return nil, err
	}
	service := Provider(jwtConfig)
	return service, nil
}

func BuildTest() (*Service, error) {
	jwtConfig, err := CfgTest()
	if err != nil {
		return nil, err
	}
	service := Provider(jwtConfig)
	return service, nil
}
