// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package meetingplatforms

import (
	"github.com/jake-hansen/agora/domain"
	"github.com/jake-hansen/agora/services/meetingplatforms/zoom"
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Build(v *viper.Viper) []*domain.MeetingPlatform {
	zoomZoom := zoom.Provide()
	v2 := Provide(zoomZoom, v)
	return v2
}
