// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package userrepo

import (
	"github.com/jake-hansen/agora/config"
	"github.com/jake-hansen/agora/database"
)

// Injectors from injector.go:

func Build() (*UserRepository, func(), error) {
	viper := config.Provide()
	databaseConfig, err := database.Cfg(viper)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := database.ProvideGORM(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	manager, err := database.Provide(databaseConfig, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := Provide(manager)
	return userRepository, func() {
		cleanup()
	}, nil
}
