// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package middleware

import (
	"github.com/gin-gonic/gin"
)

// Injectors from injector.go:

func Build() []gin.HandlerFunc {
	v := ProvideAllProductionMiddleware()
	return v
}
