// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package authservicemock

// Injectors from injector.go:

func Build() *AuthService {
	authService := Provide()
	return authService
}
