// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package oauthinforepo

import (
	"github.com/jake-hansen/agora/database"
)

// Injectors from injector.go:

func Build(manager *database.Manager) (*OAuthInfoRepo, func(), error) {
	oAuthInfoRepo := Provide(manager)
	return oAuthInfoRepo, func() {
	}, nil
}
