// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package meetingplatformrepo

import (
	"github.com/jake-hansen/agora/database"
)

// Injectors from injector.go:

func Build(manager *database.Manager) (*MeetingPlatformRepo, func(), error) {
	meetingProviderRepo := Provide(manager)
	return meetingProviderRepo, func() {
	}, nil
}
